### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by Luyao666888** [gyc-12/music-player-master#1]
汉化的不是很好哦、点击检查更新最好有个提示（点击没反应）、不能导入歌源（点击没反应）、选择音质会自动变成320k（即使自己选择的最高）

**Comment by gyc-12** [comment]
这些功能还在开发中...

**Comment by Luyao666888** [comment]
好的好的

**Comment by gyc-12** [comment]
https://github.com/gyc-12/music-player-master/releases/tag/1.0.1
