### ISSUE TITLE
不会写源有没有办法导入现成的，悲

### ISSUE THREAD

**Issue by 2022Bryant** [gyc-12/music-player-master#15]
现在属于食材和碗筷都有了，缺厨艺

**Comment by Liuyuanxua** [comment]
那就装[1.0.4](https://github.com/gyc-12/music-player-master/releases/tag/1.0.4)版本吧

**Comment by gyc-12** [comment]
https://gyc.660624.xyz/2024/09/07/CyMusic%E6%BA%90%E5%88%86%E4%BA%AB/
