### ISSUE TITLE
音源换IP了

### ISSUE THREAD

**Issue by ikun0014** [gyc-12/music-player-master#20]
http://110.42.38.239:1314

**Comment by ikun0014** [comment]
@gyc-12

**Comment by gyc-12** [comment]
感谢提醒，现在主要采用导入音源的形式。用ikun佬音源的记得关注作者更新频道。源文件可以在这里下载，后续ip过期可以自己编辑文件替换[下载](https://gyc.660624.xyz/2024/09/07/CyMusic%E6%BA%90%E5%88%86%E4%BA%AB/)
