### ISSUE TITLE
歌单名称异常

### ISSUE THREAD

**Issue by onlybeyou** [gyc-12/music-player-master#27]
感谢作者！
导入 QQ 自定义的歌单不显示名称，但删除的提示中却有名称
看下能否自定义导入的歌单名称？
![IMG_0783](https://github.com/user-attachments/assets/5078ad19-e33b-47fd-b3d9-99a2972a7348)
![IMG_0784](https://github.com/user-attachments/assets/48acbd60-20c2-4ed9-8f25-ecdbbee0635e)

**Comment by gyc-12** [comment]
把日志发一下

**Comment by onlybeyou** [comment]
> 把日志发一下

日志只有一行

![IMG_0803](https://github.com/user-attachments/assets/7cbf170b-8a5d-4e15-9c1a-992341933b44)

**Comment by gyc-12** [comment]
歌单地址方便给一个吗

**Comment by onlybeyou** [comment]
> 歌单地址方便给一个吗
好的，
https://i.y.qq.com/n2/m/share/details/taoge.html?hosteuin=7wnAoKv5oinP&id=8119020619&appversion=130900&ADTAG=wxfshare&appshare=iphone_wx

辛苦！

**Comment by gyc-12** [comment]
fixed。下个版本更新

**Comment by onlybeyou** [comment]
> fixed。下个版本更新

好的！大佬牛逼！
