### ISSUE TITLE
歌词滑动不好用

### ISSUE THREAD

**Issue by li110120999** [gyc-12/music-player-master#28]
点开歌词滑动容易出错   希望能加入指定歌词播放

**Comment by gyc-12** [comment]
下个版本优化

**Comment by li110120999** [comment]
> 下一个版本优化

还有新版本中的自动缓存歌曲到本地每次打开都是默认是  仅限本次修改

**Comment by gyc-12** [comment]
> > 下一个版本优化
> 
> 还有新版本中的自动缓存歌曲到本地每次打开都是默认是 仅限本次修改

感谢反馈🤦‍♂️

**Comment by gyc-12** [comment]
更新v1.1.1
