### ISSUE TITLE
能否支持ios本地目录，类似Nplayer、alook等。自动加载这个目录下的音频文件播放。可以在线或本地加载歌词

### ISSUE THREAD

**Issue by liuhouer** [gyc-12/music-player-master#3]
能否支持ios本地目录，类似Nplayer、alook等。自动加载这个目录下的音频文件播放。可以在线或本地加载歌词
![85a9343497d14bdaf5053242d1ba042](https://github.com/user-attachments/assets/ef83e08f-1ff7-45a6-9c39-ec6e21c72f43)
![0a4c3c49c3a0d9d438f2351c2fcf534](https://github.com/user-attachments/assets/05ab5599-6273-477a-9589-50825d37282e)

**Comment by gyc-12** [comment]
暂时不考虑本地功能，还是主打在线播放
