### ISSUE TITLE
快进快退歌词不对

### ISSUE THREAD

**Issue by Luyao666888** [gyc-12/music-player-master#4]
先快退在快进然后歌词又出问题了🙋

**Comment by gyc-12** [comment]
无法复现，我测试几首歌没问题

**Comment by Luyao666888** [comment]
> 无法复现，我测试几首歌没问题

是回退歌词不正确，不是快进，因为快进的bug修复好了，我的操作是，点进去听歌向后面拖动中间左右然后再拖到前面三十秒左右就会出现歌词播放不一致的情况，哪首歌都是一样的情况，你可以看一下
