### ISSUE TITLE
三个点选项不容易点到

### ISSUE THREAD

**Issue by Redhairrr** [gyc-12/music-player-master#40]
每首歌后面的三个点选项不容易点到，容易误操作成播放，偏偏软件又卡，就很困扰，望早日修复

**Comment by Redhairrr** [comment]
其实可以加一个左滑出选项的手势

**Comment by gyc-12** [comment]
三个点后续会扩大点击区域，你什么机型？我13pm没感觉卡呢

**Comment by Redhairrr** [comment]
我用的是iPhone15，我是导入了QQ音乐的歌单（大概1300首歌），你如果慢慢一个个往下播放不管它还好，但是你要是点击音乐，点几下就会卡了、假死的感觉，而且在favorite里面搜个搜不出来，比方说我歌单或者喜欢里面的歌一个都搜不出来；三个点可以把点击区域适当放大些，因为一点错成播放就要卡一下，我又要重启app。

**Comment by gyc-12** [comment]
> 我用的是iPhone15，我是导入了QQ音乐的歌单（大概1300首歌），你如果慢慢一个个往下播放不管它还好，但是你要是点击音乐，点几下就会卡了、假死的感觉，而且在favorite里面搜个搜不出来，比方说我歌单或者喜欢里面的歌一个都搜不出来；三个点可以把点击区域适当放大些，因为一点错成播放就要卡一下，我又要重启app。

这么多歌还没做过测试，性能应该存在问题😂，建议先减少一次性播放的歌曲数量

**Comment by gyc-12** [comment]
v1.1.2
