### ISSUE TITLE
iOS14.8，搜索音乐会点不到第一首歌曲

### ISSUE THREAD

**Issue by PungwingChan** [gyc-12/music-player-master#60]
不知道是不是个例，1.1.2版本没有问题，但更新1.1.3后搜索歌曲后会被搜索框挡住第一首歌，点击不到。系统版本iOS14.8

**Comment by gyc-12** [comment]
应该是布局问题，下个版本改下

**Comment by marry866** [comment]
> 应该是布局问题，下个版本改下

大佬，1.1.4问题依然存在

**Comment by FD63733** [comment]
大佬你好，我用1.1.2版本搜索歌曲时正常，1.1.3与1.1.4搜索完歌曲后，第一首歌点击不出来，被搜索栏挡住了，麻烦大佬解决一下。系统版本ios14.2

**Comment by FD63733** [comment]
大佬你好我是11promax，ios14.2，搜索栏第一条被遮挡

**Comment by PungwingChan** [comment]
> 应该是布局问题，下个版本改下

作者你好，实测iOS14系统更新1.1.4版本后，无法点击搜索的第一首歌曲bug依旧存在。

**Comment by FD63733** [comment]
谢谢大佬，要是优化了那真是太棒了




1451336195
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyc-12/music-player-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyc-12/music-player-master] iOS14.8，搜索音乐会点不到第一首歌曲 (Issue #60)





  
应该是布局问题，下个版本改下
  
作者你好，实测iOS14系统更新1.1.4版本后，无法点击搜索的第一首歌曲bug依旧存在。

**Comment by gyc-12** [comment]
[cymusic_test.ipa.zip](https://github.com/user-attachments/files/17702698/cymusic_test.ipa.zip)
谁来测试下

**Comment by PungwingChan** [comment]
> [cymusic_test.ipa.zip](https://github.com/user-attachments/files/17702698/cymusic_test.ipa.zip) 谁来测试下 @marry866 @PungwingChan @FD63733

已测试，感谢修复。修复的该版本号是1.1.3，希望可同步更新1.1.4版本，感谢🙏

**Comment by marry866** [comment]
> [cymusic_test.ipa.zip](https://github.com/user-attachments/files/17702698/cymusic_test.ipa.zip)
> 
> 谁来测试下 @marry866 @PungwingChan @FD63733 

感谢大佬，辛苦了，亲测己修复
