### ISSUE TITLE
没有找到可以倒入的源

### ISSUE THREAD

**Issue by Luyao666888** [gyc-12/music-player-master#7]
js格式的导入不进去，另外希望添加在线导入

**Comment by bread8314** [comment]
1.05 小白无源可用，其它的软件源用不了

**Comment by Amor-hx** [comment]
1.5 建议给提供一个源

**Comment by a86422678** [comment]
无可用音乐源，能兼容落雪源就好了，或者给小白提供一下抓取源教程就好了，感谢

**Comment by gyc-12** [comment]
https://gyc.660624.xyz/2024/09/07/CyMusic%E6%BA%90%E5%88%86%E4%BA%AB/
