### ISSUE TITLE
显示歌曲是否已经缓存的信息

### ISSUE THREAD

**Issue by zhanggaolei001** [gyc-12/music-player-master#70]
大佬好：
        给大佬提需求来了：
        希望可以添加一个标识来识别播放列表或者歌单中的歌曲是否已经被缓存过(例如显示个已经缓存过的格式图标）

**Comment by gyc-12** [comment]
收到。这个可以加

**Comment by gyc-12** [comment]
v1.1.5

**Comment by aniu2010-1124** [comment]
大佬你好，能否做一下蓝牙连接车机时显示歌词。（车机上显示歌词）谢谢
