### ISSUE TITLE
增加一个功能

### ISSUE THREAD

**Issue by JerryPei2235** [gyc-12/music-player-master#77]
遇到无高音质的音乐自动切换低一级音质播放，如果还没有，以此类推

**Comment by gyc-12** [comment]
嗯嗯，会加

**Comment by JerryPei2235** [comment]
OK

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月27日 22:12 |
| 收件人 | gyc-12/music-player-master ***@***.***> |
| 抄送人 | JerryPei2235 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [gyc-12/music-player-master] 增加一个功能 (Issue #77) |

嗯嗯，会加

**Comment by gyc-12** [comment]
v1.1.6

**Comment by JerryPei2235** [comment]
我看到了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月01日 18:35 |
| 收件人 | gyc-12/music-player-master ***@***.***> |
| 抄送人 | JerryPei2235 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [gyc-12/music-player-master] 增加一个功能 (Issue #77) |

v1.1.6
