### ISSUE TITLE
carplay无歌词显示，音量只有🐧音，易☁️等一半大小

### ISSUE THREAD

**Issue by ding2548** [gyc-12/music-player-master#8]
耳机安全降低高音量是关的，其他音乐软件的音量输出都正常，手机使用Cymusic播放音量也正常，连接carplay就只有一半的音量大小

**Comment by gyc-12** [comment]
音量这个可能跟应用内音量有关。音量条划到最右边试试试

**Comment by gyc-12** [comment]
默认音量最大

**Comment by Cheukfung** [comment]
怎么实现CarPlay的，我的CarPlay不显示这个软件
